### ISSUE TITLE
How to use `stdin`?

### ISSUE THREAD

**Issue by billksun** [foresterre/sic#1398]
I am trying to call out to `sic` from my program, feeding the image to `sic` via `stdin`. However, I keep getting the following error message:
```
Error: Unable select input/output mode: mode should either be simple xor glob
```
Inferring from the help message, I am assuming that when no `--input` or `--glob-input` is provided, `sic` will read from `stdin`, but that doesn't seem to be the case.

**Comment by foresterre** [comment]
> Inferring from the help message, I am assuming that when no `--input` or `--glob-input` is provided, `sic` will read from `stdin`, but that doesn't seem to be the case.

You are correct; this seems to be a bug, I've created a PR which should resolve this in #1400

**Comment by foresterre** [comment]
In this ascii cast I recorded an example of it working again: https://asciinema.org/a/3RXgxHh9N0JQPu4e0DpJ7VorV

NB: My linux test machine didn't have a gui attached, so I used [chafa](https://hpjansson.org/chafa/) to preview the images from within the terminal. The recording itself doesn't seem to accept everything shown in the terminal, which is why the image previews (and terminal powerline) show some artifacts, beyond the inherent limitations of `chafa`.

**Comment by foresterre** [comment]
Thanks once again for the report!

I've released https://github.com/foresterre/sic/releases/tag/v0.21.1 which should fix this issue.

**Comment by billksun** [comment]
@foresterre , thanks for fixing _and_ releasing the fix so quickly!
