### ISSUE TITLE
sic/operations: Image thresholding

### ISSUE THREAD

**Issue by MustafaSalih1993** [foresterre/sic#876]
Hello
I read about [image thresholding](https://en.wikipedia.org/wiki/Thresholding_(image_processing)) and i think i can implement it as a new operation, can i do it?, or it will not be useful for this tool

**Comment by foresterre** [comment]
I would be happy to add it! 
Do you have an idea which kind of tresholding you would like to add? :smile:

It might be that some are already implemented by third party libraries we import. For example, Otsu thresholding has been [implemented](https://docs.rs/imageproc/0.22.0/imageproc/contrast/fn.otsu_level.html) by `imageproc` which is available from the `sic_image_engine` crate. Don't let that hold you back though; I would be happy to add thresholding whether you use an already implemented technique, or want to do it yourself!

**Comment by MustafaSalih1993** [comment]
> Do you have an idea which kind of tresholding you would like to add? :smile:

Actually I have no idea, I read it generally and got only the idea 😥🤣

> It might be that some are already implemented by third party libraries we import. For example, Otsu thresholding

oh interesting I'll check it out, and do more research 😅

**Comment by MustafaSalih1993** [comment]
Update: Mind blowing! i made a little research and found many kinds of thresholding and mind blowing for cameras etc.. I'm happy i searched for that i learned a lot!
i guess the idea i had was not great _calculate intensity and then threshold the pixel_
also i checked `imageproc` implementation it's nice but i saw that it's optional crate,
now i have 2 options:
1. Implement it manually.
2. make the operation optional since if i used `imageproc` ex: `draw_text.rs` file.

what will be the best option? I'm OK with both

**Comment by foresterre** [comment]
If you would want to add Otsu thresholding I would go with the implementation in imageproc. Note that, while it's marked as optional, it's also included by default (because frankly, the crate size doesn't add that much, and drawing text is quite useful).

I'm not sure if there are other thresholding methods included in imageproc, so others may require implementing it manually anyways. 

That said, if you think you want to go for the maximum learning experience (and fun 😄) or you want to improve on the implementation in imageproc (e.g. speed wise), you can go for implementing it manually.

**Comment by MustafaSalih1993** [comment]
Sorry for the late response, work don't give me much free time 😅 ,
i guess I'll use imageproc's implementation since there's no point to implement it again and i have no idea about optimizing it 😅 , i will leave my manual implementation locally for learning only,
ill request a review by today or tomorrow
thank you

**Comment by foresterre** [comment]
Take all the time you need; there's no rush or deadline from my side 😄. Have fun!
